#!/bin/sh

# use strict error handling
set -eu

CWD=$(pwd)

bold()    { printf "\033[1m%s\033[0m" "$*"; }
success() { printf "\033[32m%s\033[0m\n" "$*"; }
info()    { printf "\033[36m%s\033[0m\n" "$*"; }
warn()    { printf "\033[33m%s\033[0m\n" "$*" 1>&2; }
error()   { printf "\033[31m%s\033[0m\n" "$*" 1>&2; }

exit_success() {
    success_message=${1:-}
    [ -n "$success_message" ] && success "$1"
    exit 0
}

exit_fail() {
    fail_message=${1:-}
    [ -n "$fail_message" ] && error "$1"
    exit 1
}

exit_fail_with_usage() {
    with_usage_message=${1:-}
    with_usage_function=${2:-}

    if [ -n "$with_usage_message" ]; then
        error "$with_usage_message"
    fi

    if [ -n "$with_usage_function" ]; then
        echo
        eval "$with_usage_function"
    fi

    exit 1
}

print_zestty_usage() {
    cat <<EOF
usage: zestty <command>

$(bold "Available commands")
help        print this message
create      create a zellij session with a name, layout, and working directory
attach      attach to an existing zellij session
list        list things that can be sessionized
EOF
}

print_create_usage() {
    cat <<EOF
usage: zestty create <name> [path] [layout]

$(bold "Parameters")
name        name of the session
path        working directory for the session, defaults to current directory
layout      name of the layout to use, default layout if not provided
EOF
}

print_attach_usage() {
    cat <<EOF
usage: zestty attach <name>

$(bold "Parameters")
name    name of the session
EOF
}

print_list_usage() {
    cat <<EOF
usage: zestty list [-z] [-a] [-d] [-p] [-w] [-s]

$(bold "Options")
-z, --zellij        list all zellij sessions
-a, --active        list only active zellij sessions
-d, --dead          list only dead zellij sessions
-p, --projects      list projects from the projects file
-w, --worktrees     list git worktrees
-s, --submodules    list git submodules
EOF
}

print_sessionize_usage() {
    cat <<EOF
usage: zestty sessionize <session>

$(bold "Builtin session types")
session     session:<name>
project     project:<name>:<path>:[layout]
worktree    worktree:<ref>:<path>
submodule   submodule:<name>:<path>
EOF
}

find_file_in_order() {
    for file in $@; do
        if [ -f "$file" ] && [ -r "$file" ]; then
            echo "$file"
            return
        fi
    done
}

find_config_file() {
    find_file_in_order \
        "$HOME/.config/zestty/config" \
        "/etc/zestty/config"
}

find_project_file() {
    find_file_in_order \
        "$HOME/.config/zestty/projects" \
        "/etc/zestty/projects"
}

get_session_state() {
    session_name="$1"
    session=$(
        zellij list-sessions --no-formatting 2> /dev/null | \
        awk "/^$session_name \[/ { print; exit }"
    )

    if [ -z "$session" ]; then
        echo "dne"
    elif echo "$session" | grep --quiet "EXITED"; then
        echo "dead"
    else
        echo "active"
    fi
}

call_zellij_switch_plugin() {
    if [ "$#" -lt "1" ]; then
        exit_fail "Session name required!"
    fi

    call_plugin_name="$1"
    call_plugin_path=${2:-}
    call_plugin_layout=${3:-}

    call_plugin_options="--session $call_plugin_name"
    if [ -n "$call_plugin_path" ] && [ -d "$call_plugin_path" ]; then
        call_plugin_options="$call_plugin_options --cwd $call_plugin_path"
    fi

    if [ -n "$call_plugin_layout" ]; then
        call_plugin_options="$call_plugin_options --layout $call_plugin_layout"
    fi

    zellij pipe --plugin zellij-switch -- "$call_plugin_options"
}

match_project_name() {
    expected_name=${1:-}

    project_file=$(find_project_file)
    [ -z "$project_file" ] && return

    while read -r project; do
        name=$(echo "$project" | cut -d "$ZESTTY_PROJECT_DELIM" -f "1")

        if [ "$expected_name" = "$name" ]; then
            echo "$project" |
            sed -e "s/$ZESTTY_PROJECT_DELIM/$ZESTTY_DELIM/g" \
                -e "s/^/project$ZESTTY_DELIM/"
            return
        fi
    done < "$project_file"
}

match_project_path() {
    expected_relpath=${1:-}
    [ -z "$expected_relpath" ] && return

    expected_relpath=$(echo "$expected_relpath" | sed "s|^~|$HOME|")
    expected_abspath=$(realpath "$expected_relpath")

    project_file=$(find_project_file)
    [ -z "$project_file" ] && return

    while read -r project; do
        relpath=$(echo "$project" | cut -d "$ZESTTY_PROJECT_DELIM" -f "2")
        relpath=$(echo "$relpath" | sed "s|^~|$HOME|")
        abspath=$(realpath "$relpath")

        if [ "$expected_abspath" = "$abspath" ]; then
            echo "$project" |
            sed -e "s/$ZESTTY_PROJECT_DELIM/$ZESTTY_DELIM/g" \
                -e "s/^/project$ZESTTY_DELIM/"
            return
        fi
    done < "$project_file"
}

create_command() {
    if [ "$#" -lt "1" ]; then
        exit_fail_with_usage \
            "Session name required!" \
            print_create_usage
    fi

    create_cwd=$CWD
    create_name="$1"
    create_path=${2:-"$create_cwd"}
    create_layout=${3:-}

    if ! [ "$(get_session_state "$create_name")" = "dne" ]; then
        exit_fail_with_usage \
            "'$create_name' already exists, use attach instead!" \
            print_attach_usage
    fi

    if ! [ -d "$create_path" ]; then
        exit_fail "'$create_path' is not a directory!"
    else
        create_path=$(realpath "$create_path")
    fi

    if [ "$ZELLIJ" = "0" ]; then
        call_zellij_switch_plugin \
            "$create_name" \
            "$create_path" \
            "$create_layout"
    else
        # pushd and popd are bash builtins and are not POSIX compliant
        cd "$create_path"

        if [ -n "$create_layout" ]; then
            zellij \
                --session "$create_name" \
                --new-session-with-layout "$create_layout"
        else
            zellij --session "$create_name"
        fi

        cd "$create_cwd"
    fi
}

attach_command() {
    if [ "$#" -lt "1" ]; then
        exit_fail_with_usage \
            "Session name required!" \
            print_attach_usage
    fi

    attach_name="$1"

    if [ "$(get_session_state "$attach_name")" = "dne" ]; then
        exit_fail_with_usage \
            "'$attach_name' does not exist, use create instead!" \
            print_create_usage
    fi

    if [ "$ZELLIJ" = "0" ]; then
        call_zellij_switch_plugin "$attach_name"
    else
        zellij attach "$attach_name"
    fi
}

list_active_sessions() {
    zellij list-sessions --no-formatting 2> /dev/null | \
    grep -v "EXITED" | \
    cut -d " " -f "1" | \
    sed "s/^/session$ZESTTY_DELIM/"
}

list_dead_sessions() {
    zellij list-sessions --no-formatting 2> /dev/null | \
    grep "EXITED" | \
    cut -d " " -f "1" | \
    sed "s/^/session$ZESTTY_DELIM/"
}

list_all_sessions() {
    zellij list-sessions --no-formatting 2> /dev/null | \
    cut -d " " -f "1" | \
    sed "s/^/session$ZESTTY_DELIM/"
}

list_projects() {
    project_file=$(find_project_file)
    if [ -z "$project_file" ]; then
        exit_fail "No project file found!"
    fi

    project_list=$(sed \
        -e "s/$ZESTTY_PROJECT_DELIM/$ZESTTY_DELIM/g" \
        -e "s/^/project$ZESTTY_DELIM/" \
        "$project_file"
    )

    if [ -z "$project_list" ]; then
        warn "Project file has no projects!"
    else
        echo "$project_list"
    fi
}

list_worktrees() {
    # TODO: use -C to check a specific directory
    git_root=$(git rev-parse --show-toplevel 2> /dev/null)
    if [ -z "$git_root" ]; then
        exit_fail "Not in a git repository, cannot list worktrees!"
    fi

    git worktree list --porcelain | \
    awk -F" " '/^worktree/ {
        path = $2;
        getline; hash = $2;
        getline;
        if ($1 == "branch") {
            sub(/refs\/heads\//, "", $2);
            printf "%s:%s\n", $2, path;
        } else if ($1 == "detached") {
            printf "%.6s:%s\n", hash, path;
        }
    }' | \
    sed -e "s/:/$ZESTTY_DELIM/g" -e "s/^/worktree$ZESTTY_DELIM/"
}

list_submodules() {
    git_root=$(git rev-parse --show-toplevel 2> /dev/null)
    if [ -z "$git_root" ]; then
        exit_fail "Not in a git repository, cannot list submodules!"
    fi

    git submodule | \
    sed -n "s/^ [a-f0-9]* \+\(.*\) \+(.*)$/\1/p" | \
    xargs -I{} realpath "$CWD/{}" | \
    sed -n "s/^\(.*\/\)\([^\/]*\)$/submodule$ZESTTY_DELIM\2$ZESTTY_DELIM\1\2/p"
}

list_command() {
    if [ "$#" -lt "1" ]; then
        exit_fail_with_usage "" print_list_usage
    fi

    got_active=1
    got_dead=1
    got_projects=1
    got_worktrees=1
    got_submodules=1
    while [ "$#" -ge "1" ]; do
        case "$1" in
            "-z" | "--zellij")
                got_active=0
                got_dead=0
                ;;
            "-a" | "--active")
                got_active=0
                ;;
            "-d" | "--dead")
                got_dead=0
                ;;
            "-p" | "--projects")
                got_projects=0
                ;;
            "-w" | "--worktrees")
                got_worktrees=0
                ;;
            "-s" | "--submodules")
                got_submodules=0
                ;;
            *)
                exit_fail_with_usage \
                    "Unknown option '$1'" \
                    print_list_usage
                ;;
        esac

        shift
    done

    if [ "$got_active" = "0" ] && [ "$got_dead" = "0" ]; then
        list_all_sessions
    elif [ "$got_active" = "0" ]; then
        list_active_sessions
    elif [ "$got_dead" = "0" ]; then
        list_dead_sessions
    fi

    [ "$got_projects" = "0" ] && list_projects
    [ "$got_worktrees" = "0" ] && list_worktrees
    [ "$got_submodules" = "0" ] && list_submodules

    return 0
}

sessionize_session() {
    session_name=${1:-}
    [ -z "$session_name" ] && exit_fail "Session name required!"

    session_project=$(match_project_name "$session_name")
    if [ -n "$session_project" ]; then
        sessionize_command "$session_project"
        return
    fi

    session_state=$(get_session_state "$session_name")
    case "$session_state" in
        "dne")
            exit_fail "Session '$session_name' no longer exists!"
            ;;
        "dead" | "active")
            attach_command "$session_name"
            ;;
    esac
}

sessionize_project() {
    project_name=${1:-}
    project_path=${2:-}
    project_layout=${3:-}

    if [ -z "$project_name" ]; then
        exit_fail "Project name required!"
    elif [ -z "$project_path" ]; then
        exit_fail "Project path required!"
    fi

    project_abspath=$(echo "$project_path" | sed "s|^~|$HOME|")
    project_abspath=$(realpath "$project_abspath")
    if ! [ -d "$project_abspath" ]; then
        exit_fail "Project path must be a directory!"
    fi

    session_state=$(get_session_state "$project_name")
    case "$session_state" in
        "dne")
            create_command "$project_name" "$project_abspath" "$project_layout"
            ;;
        "dead")
            zellij delete-session "$project_name" > /dev/null
            create_command "$project_name" "$project_abspath" "$project_layout"
            ;;
        "active")
            attach_command "$project_name"
            ;;
    esac
}

sessionize_worktree() {
    worktree_path=${2:-}

    if [ -z "$worktree_path" ]; then
        exit_fail "Worktree path required!"
    elif ! [ -d "$worktree_path" ]; then
        exit_fail "Project path must be a directory!"
    fi

    worktree_project=$(match_project_path "$worktree_path")
    if [ -n "$worktree_project" ]; then
        sessionize_command "$worktree_project"
        return
    fi

    worktree_name=$(basename "$worktree_path")
    worktree_session_state=$(get_session_state "$worktree_name")
    case "$worktree_session_state" in
        "dne")
            create_command "$worktree_name" "$worktree_path"
            ;;
        "dead" | "active")
            attach_command "$worktree_name"
            ;;
    esac
}

sessionize_submodule() {
    submodule_name=${1:-}
    submodule_path=${2:-}
    submodule_layout=""

    if [ -z "$submodule_name" ]; then
        exit_fail "Submodule name required!"
    elif [ -z "$submodule_path" ]; then
        exit_fail "Submodule path required!"
    fi

    submodule_project=$(match_project_name "$submodule_name")
    if [ -n "$submodule_project" ]; then
        # split project for path and layout
        sessionize_old_delimiter=$IFS
        IFS="$ZESTTY_DELIM"
        set -- $submodule_project
        IFS="$sessionize_old_delimiter"

        # get rid of type
        shift

        submodule_name="$1_$submodule_name"
        submodule_layout="$3"
    else
        submodule_project=$(match_project_path "$submodule_path")
        if [ -n "$submodule_project" ]; then
            sessionize_command "$submodule_project"
            return
        fi
    fi

    submodule_session_state=$(get_session_state "$submodule_name")
    case "$submodule_session_state" in
        "dne")
            create_command "$submodule_name" "$submodule_path" "$submodule_layout"
            ;;
        "dead" | "active")
            attach_command "$submodule_name"
            ;;
    esac
}

sessionize_command() {
    sessionize_session=${1:-}
    if [ -z "$sessionize_session" ]; then
        exit_fail_with_usage \
            "A session is required!" \
            print_sessionize_usage
    fi

    # split into arguments for sessionize functions
    sessionize_old_delimiter=$IFS
    IFS="$ZESTTY_DELIM"
    set -- $sessionize_session
    IFS="$sessionize_old_delimiter"

    # pop the type off the arguments
    sessionize_type=${1:-}
    shift

    case "$sessionize_type" in
        "session")
            sessionize_session "$@"
            ;;
        "project")
            sessionize_project "$@"
            ;;
        "worktree")
            sessionize_worktree "$@"
            ;;
        "submodule")
            sessionize_submodule "$@"
            ;;
        *)
            exit_fail_with_usage \
                "A session type is required!" \
                print_sessionize_usage
            ;;
    esac
}

# do not proceed if config is invalid
if ! zellij setup --check 1> /dev/null; then
    exit_fail
fi

if [ "$#" -lt "1" ]; then
    exit_fail_with_usage "" print_zestty_usage
fi

command="$1"
shift

# if we are not in a zellij session, explicitly set the ZELLIJ environment
# variable to 1 so that we can use it in conditionals later
ZELLIJ=${ZELLIJ:-1}

# save config from environment
ZESTTY_DELIM_ENV=${ZESTTY_DELIM:-}
ZESTTY_PROJECT_DELIM_ENV=${ZESTTY_PROJECT_DELIM:-}

config_file=$(find_config_file)
if [ -n "$config_file" ]; then
    source "$config_file"
fi

# set to default if not in configured
ZESTTY_DELIM=${ZESTTY_DELIM:-":"}
ZESTTY_PROJECT_DELIM=${ZESTTY_PROJECT_DELIM:-":"}

# prefer values from environment
if [ -n "$ZESTTY_DELIM_ENV" ]; then
    ZESTTY_DELIM=$ZESTTY_DELIM_ENV
fi

if [ -n "$ZESTTY_PROJECT_DELIM_ENV" ]; then
    ZESTTY_PROJECT_DELIM=$ZESTTY_PROJECT_DELIM_ENV
fi

case "$command" in
    "-?" | "-h" | "--help" | "help")
        print_zestty_usage
        ;;
    "create")
        create_command "$@"
        ;;
    "attach")
        attach_command "$@"
        ;;
    "list")
        list_command "$@"
        ;;
    "sessionize")
        sessionize_command "$@"
        ;;
    *)
        exit_fail_with_usage \
            "Unknown command '$command'" \
            print_zestty_usage
esac

exit_success
