#!/bin/sh

# use strict error handling
set -eu

CWD=$(pwd)

bold()    { printf "\033[1m%s\033[0m" "$*"; }
success() { printf "\033[32m%s\033[0m\n" "$*"; }
info()    { printf "\033[36m%s\033[0m\n" "$*"; }
warn()    { printf "\033[33m%s\033[0m\n" "$*" 1>&2; }
error()   { printf "\033[31m%s\033[0m\n" "$*" 1>&2; }

exit_success() {
    [ -n "${1-}" ] && success "$1"
    exit 0
}

exit_fail() {
    [ -n "${1-}" ] && error "$1"
    exit 1
}

exit_fail_with_usage() {
    _efwu_message=${1:-}
    _efwu_function=${2:-}

    if [ -n "$_efwu_message" ]; then
        error "$_efwu_message"
        [ -n "$_efwu_function" ] && echo
    fi

    [ -n "$_efwu_function" ] && eval "$_efwu_function"
    exit 1
}

zestty_usage() {
    cat <<EOF
usage: zestty <command>

$(bold "Available commands")
help        print this message
create      create a zellij session with a name, layout, and working directory
attach      attach to an existing zellij session
pick        pick from lists and sessionize
list        list things that can be sessionized
sessionize  create or attach to a session object
EOF
}

zestty_create_usage() {
    cat <<EOF
usage: zestty create <name> [path] [layout]

$(bold "Parameters")
name        name of the session
path        working directory for the session, defaults to current directory
layout      name of the layout to use, default layout if not provided
EOF
}

zestty_attach_usage() {
    cat <<EOF
usage: zestty attach <name>

$(bold "Parameters")
name    name of the session
EOF
}

zestty_pick_usage() {
    cat <<EOF
usage: zestty pick <z | a | d | p | w | s> [query]

$(bold "Pickers")
z, zellij        pick zellij sessions
a, active        pick only active zellij sessions
d, dead          pick only dead zellij sessions
p, projects      pick projects from the projects file
w, worktrees     pick git worktrees
s, submodules    pick git submodules

$(bold "Parameters")
query   initial query for fuzzy finder
EOF
}

zestty_list_usage() {
    cat <<EOF
usage: zestty list [z] [a] [d] [p] [w] [s]

$(bold "Lists")
z, zellij        list all zellij sessions
a, active        list only active zellij sessions
d, dead          list only dead zellij sessions
p, projects      list projects from the projects file
w, worktrees     list git worktrees
s, submodules    list git submodules
EOF
}

zestty_sessionize_usage() {
    cat <<EOF
usage: zestty sessionize <session>

$(bold "Builtin session types")
session     session:<name>:<state>
project     project:<name>:<path>:[layout]
worktree    worktree:<ref>:<path>
submodule   submodule:<name>:<path>

$(bold "Parameters")
session     session object to sessionize
EOF
}

zestty_find_file_in_order() {
    for _ffio_file in "$@"; do
        if [ -f "$_ffio_file" ] && [ -r "$_ffio_file" ]; then
            echo "$_ffio_file"
            return
        fi
    done
}

zestty_find_config_file() {
    zestty_find_file_in_order \
        "$HOME/.config/zestty/config" \
        "/etc/zestty/config"
}

zestty_find_project_file() {
    zestty_find_file_in_order \
        "$HOME/.config/zestty/projects" \
        "/etc/zestty/projects"
}

zestty_get_session_state() {
    _gss_name="$1"
    _gss_session=$(
        command zellij list-sessions --no-formatting 2> /dev/null | \
        awk "/^$_gss_name \[/ { print; exit }"
    )

    if [ -z "$_gss_session" ]; then
        echo "dne"
    elif echo "$_gss_session" | grep --quiet "EXITED"; then
        echo "dead"
    else
        echo "active"
    fi
}

zestty_call_switch() {
    if [ "$#" -lt "1" ]; then
        exit_fail "Session name required!"
    fi

    _cs_name="$1"
    _cs_path=${2:-}
    _cs_layout=${3:-}

    _cs_options="{ \"command\": \"switch\", \"name\": \"$_cs_name\""
    if [ -n "$_cs_path" ] && [ -d "$_cs_path" ]; then
        _cs_options="$_cs_options, \"path\": \"$_cs_path\""
    fi

    if [ -n "$_cs_layout" ]; then
        _cs_options="$_cs_options, \"layout\": \"$_cs_layout\""
    fi

    _cs_options="$_cs_options }"
    exec zellij pipe --plugin "$ZESTTY_PLUGIN_URL" -- "$_cs_options"
}

zestty_match_project_name() {
    _mpn_expected_name=${1:-}

    _mpn_project_file=$(zestty_find_project_file)
    [ -z "$_mpn_project_file" ] && return

    while read -r _mpn_project; do
        _mpn_actual_name=$(echo "$_mpn_project" | cut -d "$ZESTTY_PROJECT_DELIM" -f "1")

        if [ "$_mpn_expected_name" = "$_mpn_actual_name" ]; then
            echo "$_mpn_project" |
            sed -e "s/$ZESTTY_PROJECT_DELIM/$ZESTTY_DELIM/g" \
                -e "s/^/project$ZESTTY_DELIM/"
            return
        fi
    done < "$_mpn_project_file"
}

zestty_match_project_path() {
    _mpp_expected_relpath=${1:-}
    [ -z "$_mpp_expected_relpath" ] && return

    _mpp_expected_relpath=$(echo "$_mpp_expected_relpath" | sed "s|^~|$HOME|")
    _mpp_expected_abspath=$(realpath "$_mpp_expected_relpath")

    _mpp_project_file=$(zestty_find_project_file)
    [ -z "$_mpp_project_file" ] && return

    while read -r _mpp_project; do
        _mpp_actual_relpath=$(echo "$_mpp_project" | cut -d "$ZESTTY_PROJECT_DELIM" -f "2")
        _mpp_actual_relpath=$(echo "$_mpp_actual_relpath" | sed "s|^~|$HOME|")
        _mpp_actual_abspath=$(realpath "$_mpp_actual_relpath")

        if [ "$_mpp_expected_abspath" = "$_mpp_actual_abspath" ]; then
            echo "$_mpp_project" |
            sed -e "s/$ZESTTY_PROJECT_DELIM/$ZESTTY_DELIM/g" \
                -e "s/^/project$ZESTTY_DELIM/"
            return
        fi
    done < "$_mpp_project_file"
}

zestty_create() {
    if [ "$#" -lt "1" ]; then
        exit_fail_with_usage \
            "Session name required!" \
            zestty_create_usage
    fi

    _c_cwd=$CWD
    _c_name="$1"
    _c_path=${2:-"$_c_cwd"}
    _c_layout=${3:-}

    case "$_c_name" in
        "-?" | "-h" | "--help")
            zestty_create_usage
            exit_success
            ;;
    esac

    if ! [ "$(zestty_get_session_state "$_c_name")" = "dne" ]; then
        exit_fail_with_usage \
            "'$_c_name' already exists, use attach instead!" \
            zestty_attach_usage
    fi

    if ! [ -d "$_c_path" ]; then
        exit_fail "'$_c_path' is not a directory!"
    else
        _c_path=$(realpath "$_c_path")
    fi

    if [ "$ZELLIJ" = "0" ]; then
        zestty_call_switch \
            "$_c_name" \
            "$_c_path" \
            "$_c_layout"
    else
        # pushd and popd are bash builtins and are not POSIX compliant
        cd "$_c_path"

        if [ -n "$_c_layout" ]; then
            exec zellij \
                --session "$_c_name" \
                --new-session-with-layout "$_c_layout"
        else
            exec zellij --session "$_c_name"
        fi

        cd "$_c_cwd"
    fi
}

zestty_attach() {
    if [ "$#" -lt "1" ]; then
        exit_fail_with_usage \
            "Session name required!" \
            zestty_attach_usage
    fi

    _a_name="$1"

    case "$_a_name" in
        "-?" | "-h" | "--help")
            zestty_attach_usage
            exit_success
            ;;
    esac

    if [ "$(zestty_get_session_state "$_a_name")" = "dne" ]; then
        exit_fail_with_usage \
            "'$_a_name' does not exist, use create instead!" \
            zestty_create_usage
    fi

    if [ "$ZELLIJ" = "0" ]; then
        zestty_call_switch "$_a_name"
    else
        exec zellij attach "$_a_name"
    fi
}

zestty_base_picker() {
    _bp_query=${1-}
    [ -z "$_bp_query" ] && _bp_select_option="" || _bp_select_option="--select-1"
    shift

    _bp_fzf=$(command -v fzf)
    if [ -z "$_bp_fzf" ]; then
        exit_fail_with_usage \
            "$(bold fzf) is required for fuzzy finding!" \
            zestty_pick_usage
    fi

    "$_bp_fzf" --query="$_bp_query" \
        --delimiter="$ZESTTY_DELIM" \
        --layout=reverse --info=hidden --no-separator \
        --no-multi $_bp_select_option --cycle \
        --height=7 --ansi --color=16 \
        "$@"
}

zestty_name_picker() {
    _np_query=${1-}
    shift
    zestty_base_picker "$_np_query" --with-nth="2" "$@"
}

zestty_transform_picker() {
    _tp_query=${1-}
    _tp_transform=${2-}
    shift 2
    zestty_base_picker "$_tp_query" --with-nth="$_tp_transform" --nth="1"
}

zestty_pick() {
    if [ "$#" -lt "1" ]; then
        exit_fail_with_usage "" zestty_pick_usage
    fi

    _p_list="$1"
    shift
    _p_query="$*"

    ZESTTY_DELIM=$(printf "\t")
    case "$_p_list" in
        "-?" | "-h" | "--help" | "h" | "help")
            zestty_pick_usage
            exit_success
            ;;
        "z" | "zellij")
            _p_selected=$(
                { zestty_list_active; zestty_list_dead; } |
                zestty_transform_picker "$_p_query" "{2}${ZESTTY_DELIM}[{3}]" \
                    --header="zellij"
            )
            ;;
        "a" | "active")
            _p_selected=$(
                zestty_list_active |
                zestty_name_picker "$_p_query" --header="active"
            )
            ;;
        "d" | "dead")
            _p_selected=$(
                zestty_list_dead |
                zestty_name_picker "$_p_query" --header="dead"
            )
            ;;
        "p" | "projects")
            _p_selected=$(
                zestty_list_projects |
                zestty_transform_picker "$_p_query" "{2}${ZESTTY_DELIM}({3})" \
                    --header="projects"
            )
            ;;
        "w" | "worktrees")
            _p_selected=$(
                zestty_list_worktrees |
                zestty_transform_picker "$_p_query" "{3}${ZESTTY_DELIM}({2})" \
                    --header="worktrees"
            )
            ;;
        "s" | "submodules")
            _p_selected=$(
                zestty_list_submodules |
                zestty_transform_picker "$_p_query" "{2}${ZESTTY_DELIM}({3})" \
                    --header="submodules"
            )
            ;;
        *)
            exit_fail_with_usage \
                "Unknown option '$_p_list'" \
                zestty_pick_usage
            ;;
    esac

    if [ -n "$_p_selected" ]; then
        zestty_sessionize "$_p_selected"
    fi

    return 0
}

zestty_list_active() {
    zellij list-sessions --no-formatting 2> /dev/null | \
    grep -v "EXITED" | \
    cut -d " " -f "1" | \
    sed -e "s/^/session$ZESTTY_DELIM/" \
        -e "s/$/${ZESTTY_DELIM}active/"
}

zestty_list_dead() {
    zellij list-sessions --no-formatting 2> /dev/null | \
    grep "EXITED" | \
    cut -d " " -f "1" | \
    sed -e "s/^/session$ZESTTY_DELIM/" \
        -e "s/$/${ZESTTY_DELIM}dead/"
}

zestty_list_projects() {
    _lp_project_file=$(zestty_find_project_file)
    if [ -z "$_lp_project_file" ]; then
        exit_fail "No project file found!"
    fi

    _lp_project_list=$(sed \
        -e "s/$ZESTTY_PROJECT_DELIM/$ZESTTY_DELIM/g" \
        -e "s/^/project$ZESTTY_DELIM/" \
        "$_lp_project_file"
    )

    if [ -z "$_lp_project_list" ]; then
        warn "Project file has no projects!"
    else
        echo "$_lp_project_list"
    fi
}

zestty_list_worktrees() {
    # TODO: use -C to check a specific directory
    _lw_git_root=$(git rev-parse --show-toplevel 2> /dev/null)
    if [ -z "$_lw_git_root" ]; then
        exit_fail "Not in a git repository, cannot list worktrees!"
    fi

    git worktree list --porcelain | \
    awk -F" " '/^worktree/ {
        path = $2;
        getline; hash = $2;
        getline;
        if ($1 == "branch") {
            sub(/refs\/heads\//, "", $2);
            printf "%s:%s\n", $2, path;
        } else if ($1 == "detached") {
            printf "%.6s:%s\n", hash, path;
        }
    }' | \
    sed -e "s/:/$ZESTTY_DELIM/g" -e "s/^/worktree$ZESTTY_DELIM/"
}

zestty_list_submodules() {
    _ls_git_root=$(git rev-parse --show-toplevel 2> /dev/null)
    if [ -z "$_ls_git_root" ]; then
        exit_fail "Not in a git repository, cannot list submodules!"
    fi

    git submodule | \
    sed -n "s/^ [a-f0-9]* \+\(.*\) \+(.*)$/\1/p" | \
    xargs -I{} realpath "$CWD/{}" | \
    sed -n "s/^\(.*\/\)\([^\/]*\)$/submodule$ZESTTY_DELIM\2$ZESTTY_DELIM\1\2/p"
}

zestty_list() {
    if [ "$#" -lt "1" ]; then
        exit_fail_with_usage "" zestty_list_usage
    fi

    _l_active=1
    _l_dead=1
    _l_projects=1
    _l_worktrees=1
    _l_submodules=1
    while [ "$#" -ge "1" ]; do
        case "$1" in
            "-?" | "-h" | "--help" | "h" | "help")
                zestty_list_usage
                exit_success
                ;;
            "z" | "zellij") _l_active=0; _l_dead=0;;
            "a" | "active") _l_active=0;;
            "d" | "dead") _l_dead=0;;
            "p" | "projects") _l_projects=0;;
            "w" | "worktrees") _l_worktrees=0;;
            "s" | "submodules") _l_submodules=0;;
            *)
                exit_fail_with_usage \
                    "Unknown option '$1'" \
                    zestty_list_usage
                ;;
        esac

        shift
    done

    [ "$_l_active" = "0" ] && zestty_list_active
    [ "$_l_dead" = "0" ] && zestty_list_dead
    [ "$_l_projects" = "0" ] && zestty_list_projects
    [ "$_l_worktrees" = "0" ] && zestty_list_worktrees
    [ "$_l_submodules" = "0" ] && zestty_list_submodules

    return 0
}

zestty_sessionize_session() {
    _ss_name=${1:-}
    [ -z "$_ss_name" ] && exit_fail "Session name required!"

    _ss_project=$(zestty_match_project_name "$_ss_name")
    if [ -n "$_ss_project" ]; then
        zestty_sessionize "$_ss_project"
        return
    fi

    _ss_state=$(zestty_get_session_state "$_ss_name")
    case "$_ss_state" in
        "dne") exit_fail "Session '$_ss_name' no longer exists!";;
        "dead" | "active") zestty_attach "$_ss_name";;
    esac
}

zestty_sessionize_project() {
    _sp_name=${1:-}
    _sp_path=${2:-}
    _sp_layout=${3:-}

    if [ -z "$_sp_name" ]; then
        exit_fail "Project name required!"
    elif [ -z "$_sp_path" ]; then
        exit_fail "Project path required!"
    fi

    _sp_abspath=$(echo "$_sp_path" | sed "s|^~|$HOME|")
    _sp_abspath=$(realpath "$_sp_abspath")
    if ! [ -d "$_sp_abspath" ]; then
        exit_fail "Project path must be a directory!"
    fi

    _sp_state=$(zestty_get_session_state "$_sp_name")
    case "$_sp_state" in
        "dne") zestty_create "$_sp_name" "$_sp_abspath" "$_sp_layout";;
        "dead")
            zellij delete-session "$_sp_name" > /dev/null
            zestty_create "$_sp_name" "$_sp_abspath" "$_sp_layout"
            ;;
        "active") zestty_attach "$_sp_name";;
    esac
}

zestty_sessionize_worktree() {
    _sw_path=${2:-}

    if [ -z "$_sw_path" ]; then
        exit_fail "Worktree path required!"
    elif ! [ -d "$_sw_path" ]; then
        exit_fail "Project path must be a directory!"
    fi

    _sw_project=$(zestty_match_project_path "$_sw_path")
    if [ -n "$_sw_project" ]; then
        zestty_sessionize "$_sw_project"
        return
    fi

    _sw_name=$(basename "$_sw_path")
    _sw_state=$(zestty_get_session_state "$_sw_name")
    case "$_sw_state" in
        "dne") zestty_create "$_sw_name" "$_sw_path";;
        "dead" | "active") zestty_attach "$_sw_name";;
    esac
}

zestty_sessionize_submodule() {
    _su_name=${1:-}
    _su_path=${2:-}
    _su_layout=""

    if [ -z "$_su_name" ]; then
        exit_fail "Submodule name required!"
    elif [ -z "$_su_path" ]; then
        exit_fail "Submodule path required!"
    fi

    _su_project=$(zestty_match_project_name "$_su_name")
    if [ -n "$_su_project" ]; then
        # split project for path and layout
        _su_old_delim=$IFS
        IFS="$ZESTTY_DELIM"
        set -- $_su_project
        IFS="$_su_old_delim"

        # get rid of type
        shift

        _su_name="$1_$_su_name"
        _su_layout="$3"
    else
        _su_project=$(zestty_match_project_path "$_su_path")
        if [ -n "$_su_project" ]; then
            zestty_sessionize "$_su_project"
            return
        fi
    fi

    _su_state=$(zestty_get_session_state "$_su_name")
    case "$_su_state" in
        "dne") zestty_create "$_su_name" "$_su_path" "$_su_layout";;
        "dead" | "active") zestty_attach "$_su_name";;
    esac
}

zestty_sessionize() {
    _s_session=${1:-}
    if [ -z "$_s_session" ]; then
        exit_fail_with_usage \
            "A session is required!" \
            zestty_sessionize_usage
    fi

    case "$_s_session" in
        "-?" | "-h" | "--help" | "h" | "help")
            zestty_sessionize_usage
            exit_success
            ;;
    esac

    # split into arguments for sessionize functions
    _s_old_delim=$IFS
    IFS="$ZESTTY_DELIM"
    set -- $_s_session
    IFS="$_s_old_delim"

    # pop the type off the arguments
    _s_type=${1:-}
    shift

    case "$_s_type" in
        "session") zestty_sessionize_session "$@";;
        "project") zestty_sessionize_project "$@";;
        "worktree") zestty_sessionize_worktree "$@";;
        "submodule") zestty_sessionize_submodule "$@";;
        *) exit_fail_with_usage "A session type is required!" zestty_sessionize_usage;;
    esac
}

# do not proceed if config is invalid
if ! zellij setup --check 1> /dev/null; then
    exit_fail
fi

if [ "$#" -lt "1" ]; then
    exit_fail_with_usage "" zestty_usage
fi

_z_command="$1"
shift

# if we are not in a zellij session, explicitly set the ZELLIJ environment
# variable to 1 so that we can use it in conditionals later
ZELLIJ=${ZELLIJ:-1}

# save config from environment
ZESTTY_DELIM_ENV=${ZESTTY_DELIM:-}
ZESTTY_PROJECT_DELIM_ENV=${ZESTTY_PROJECT_DELIM:-}
ZESTTY_PLUGIN_URL_ENV=${ZESTTY_PLUGIN_URL:-}

_z_config_file=$(zestty_find_config_file)
if [ -n "$_z_config_file" ]; then
    . "$_z_config_file"
fi

# set to default if not configured
ZESTTY_DELIM=${ZESTTY_DELIM:-":"}
ZESTTY_PROJECT_DELIM=${ZESTTY_PROJECT_DELIM:-":"}
ZESTTY_PLUGIN_URL=${ZESTTY_PLUGIN_URL:-"https://github.com/aidantlynch00/zestty/releases/latest/download/zestty.wasm"}

# prefer values from environment
if [ -n "$ZESTTY_DELIM_ENV" ]; then
    ZESTTY_DELIM=$ZESTTY_DELIM_ENV
fi

if [ -n "$ZESTTY_PROJECT_DELIM_ENV" ]; then
    ZESTTY_PROJECT_DELIM=$ZESTTY_PROJECT_DELIM_ENV
fi

if [ -n "$ZESTTY_PLUGIN_URL_ENV" ]; then
    ZESTTY_PLUGIN_URL=$ZESTTY_PLUGIN_URL_ENV
fi

case "$_z_command" in
    "-?" | "-h" | "--help" | "h" | "help") zestty_usage;;
    "c" | "create") zestty_create "$@";;
    "a" | "attach") zestty_attach "$@";;
    "p" | "pick") zestty_pick "$@";;
    "l" | "list") zestty_list "$@";;
    "s" | "sessionize") zestty_sessionize "$@";;
    *) exit_fail_with_usage "Unknown command '$_z_command'" zestty_usage;;
esac

exit_success
