#!/bin/sh

# use strict error handling
set -eu

bold()    { printf "\033[1m%s\033[0m" "$*"; }
success() { printf "\033[32m%s\033[0m\n" "$*"; }
info()    { printf "\033[36m%s\033[0m\n" "$*"; }
warn()    { printf "\033[33m%s\033[0m\n" "$*" 1>&2; }
error()   { printf "\033[31m%s\033[0m\n" "$*" 1>&2; }

exit_success() {
    if [ "$#" -ge "1" ] && [ -n "$1" ]; then
        success "$1"
    fi

    exit 0
}

exit_fail() {
    if [ -n "$1" ]; then
        error "$1"
    fi

    exit 1
}

print_zestty_usage() {
    echo "$(cat <<EOF
usage: zestty [command]

$(bold "Available commands")
help        print this message
EOF
    )"
}

if [ "$#" -lt "1" ]; then
    print_zestty_usage
    exit_success
fi

command="$1"
shift

case "$command" in
    "-?" | "-h" | "--help" | "help")
        print_zestty_usage
        ;;
esac

exit_success
